name: CI

on:
  pull_request:
  push:

jobs:
  tox:
    name: isolated chatmaild tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: run chatmaild tests 
        working-directory: chatmaild
        run: pipx run tox

  scripts:
    name: deploy-chatmail tests 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: initenv 
        run: scripts/initenv.sh

      - name: run formatting checks 
        run: venv/bin/cmdeploy fmt -v 

      - name: run deploy-chatmail offline tests 
        working-directory: deploy-chatmail
        run: venv/bin/pytest tests

      - name: initialize with chatmail domain
        run: venv/bin/cmdeploy init chat.example.org  

      # all other cmdeploy commands require a staging server 
      # see https://github.com/deltachat/chatmail/issues/100
